const pathNameMap = {
  'guide-account': 'Account',
  'guide-accordion': 'Accordion',
  'guide-agree': 'Agree Form',
  'guide-aggrid': 'Ag Grid',
  'guide-badge': 'Badge',
  'guide-button': 'Button',
  'guide-chatbot': 'Chatbot',
  'guide-checkbox': 'Checkbox',
  'guide-form': 'Form',
  'guide-list': 'List',
  'guide-login': 'Login',
  'guide-radio': 'Radio',
  'guide-product': 'Product',
  'guide-popup': 'Popup',
  'guide-search': 'Search Form',
  'guide-select': 'Select Box',
  'guide-scroll': 'Scroll',
  'guide-tabs': 'Tabs',
  'guide-textfield': 'Text Field',
  'guide-title': 'Title',
  'guide-transfer': 'Transfer',
  'guide-typograph': 'Typography',
};

export default pathNameMap;
